---
title: "EDS223: Week 1 Lab"
author: "Eva Newby"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
# install.packages('sf') #vector data
# install.packages("stars") # raster data
# install.packages("tmap") # map making
# install.packages("here") # file paths
```

```{r}
library(sf)
library(stars)
library(tmap)
library(here)
```

```{r}
# read in a raster of global elevation
world_elevation <- read_stars(here("data", "worldelevation.tif"))

# country boundaries
world_vector <- read_sf(here("data", 'worldvector.gpkg'))

# major cities
world_cities <- read_sf(here('data', 'worldcities.gpkg'))
```

```{r}

tm_shape(world_elevation, bbox = world_cities)+
  tm_raster()+
tm_shape(world_vector) + 
  tm_borders() 
  
```

```{r}
tm_shape(world_vector)+
  tm_polygons(col = 'lightblue',
              border.col = "black",
              lwd = 0.5,
              lty = "dashed") 
  # tm_polgyons colors in light gray with dark gray borders

```

```{r}
tm_shape(world_vector) +
  tm_borders( col = 'red')
```

```{r}
tm_shape(world_vector) +
  tm_fill( col = 'lightblue')
```

```{r}
tm_shape(world_vector) +
  tm_fill('CO2_emissions')
```

```{r}
tm_shape(world_cities) +
  tm_symbols()
```

```{r}
tm_shape(world_vector) +
  tm_polygons('life_expectancy',
              palette = c('yellow', 'darkgreen'),
              title = "Life Expectancy (years)")
```

```{r}
# exploring color palettes 
# install.packages("viridisLite")
```

```{r}
library(viridisLite)
```

```{r}
#manipulate using color
tm_shape(world_vector) +
  tm_polygons('life_expectancy',
              palette = viridis(option = "plasma", 8),
              title = "Life Expectancy (years)")
```

```{r}
# manipulate using size

tm_shape(world_vector) +
  tm_polygons() +
  tm_shape(world_cities)+
  tm_symbols(size = 'pop2020',
             legend.size.is.portrait = TRUE)

```

```{r}
tm_shape(world_vector) +
  tm_graticules() + # converts to lat long 
  tm_fill() 
```

```{r}
tm_shape(world_vector) +
  tm_fill()+
  tm_scale_bar()+
  tm_compass(position = c('left', 'top'))
```

```{r}
#Let's make our map interactive using tmap_mode
tmap_mode('view')


map1 <- tm_shape(world_vector) +
  tm_fill(col = 'wb_income_region',
          palette = viridisLite::plasma(5),
                            title = 'Regional Income')+
  tm_layout(bg.color = 'grey95',
            main.title = 'Global Income by Country',
            frame = FALSE)
```

```{r}
tmap_mode('view')


map1 <- tm_shape(world_vector) +
  tm_fill(col = 'wb_income_region',
          palette = viridisLite::plasma(5),
                            title = 'Regional Income')+
  tm_layout(bg.color = 'grey95',
            main.title = 'Global Income by Country',
            frame = FALSE)

tmap_save(map1, here('tmap-example.png'))
```
