---
title: "Week 1 Discussion"
author: "Eva Newby"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---
```{r}
# Load packages
library(here)
library(tidyverse)
library(stars)
library(sf)
library(tmap)
library(viridisLite)
```

```{r}
ei_points <- sf::read_sf(here::here("data", "easter_island", "ei_points.gpkg"))
volcanoes <- subset(ei_points, type == "volcano")
ei_elev <- stars::read_stars(here::here("data", "easter_island", "ei_elev.tif"))
ei_borders <- sf::read_sf(here::here("data", "easter_island", "ei_border.gpkg"))
ei_roads <- sf::read_sf(here::here("data", "easter_island", "ei_roads.gpkg"))
```

Create a map of Easter Island

```{r}
tm_shape(ei_borders)+
  tm_polygons()+
```

Create a map of Easter Island and…
…denote the island’s borders and continuous elevation
…denote the island’s volcanoes and roads
…play with the color palette and essential map elements
Create an interactive map of Easter Island

```{r}
#tmap_mode('view')
tmap_mode('plot')

tm_shape(ei_elev)+
  tm_raster(palette = c("#0B8A26", "#D4EBD9"),
            title = 'Elevation (meters amsl)')+  # map of elevation 
  tm_shape(ei_borders)+
  tm_borders()+  # map of Easter island
tm_shape(volcanoes)+
  tm_dots(col = 'red', size = .1)+  # volcanoes
tm_shape(ei_roads)+
  tm_lines()+ # roads
  tm_scale_bar(position = c('left', 'bottom'))+
  tm_compass() +
  tm_layout(bg.color = 'grey95',
            main.title = 'Elevation on Easter Island',
            frame = FALSE)
  #tm_legend(layout())
  
  
```

